export const APP_PERMISSIONS = [
   'workspace.create',
   'workspace.delete',
   'workspace.invite.create',
   'workspace.invite.delete',
   'workspace.invite.list',
   'workspace.invite.read',
   'workspace.invite.revoke',
   'workspace.invite.update',
   'workspace.list',
   'workspace.permission.assign',
   'workspace.read',
   'workspace.update',
   'workspace.user.create',
   'workspace.user.delete',
   'workspace.user.list',
   'workspace.user.read',
   'workspace.user.update',
   'user.address.create',
   'user.address.delete',
   'user.address.list',
   'user.address.read',
   'user.address.update',
   'user.create',
   'user.delete',
   'user.document.create',
   'user.document.delete',
   'user.document.list',
   'user.document.read',
   'user.document.update',
   'user.email.create',
   'user.email.delete',
   'user.email.list',
   'user.email.read',
   'user.email.update',
   'user.list',
   'user.phone.create',
   'user.phone.delete',
   'user.phone.list',
   'user.phone.read',
   'user.phone.update',
   'user.read',
   'user.update',
   'application.create',
   'application.delete',
   'application.list',
   'application.permission.assign',
   'application.permission.create',
   'application.permission.delete',
   'application.permission.list',
   'application.permission.read',
   'application.permission.update',
   'application.read',
   'application.role.create',
   'application.role.delete',
   'application.role.list',
   'application.role.permission.create',
   'application.role.permission.delete',
   'application.role.permission.list',
   'application.role.permission.read',
   'application.role.permission.update',
   'application.role.read',
   'application.role.update',
   'application.update',
   'oauth.client.create',
   'oauth.client.delete',
   'oauth.client.grant-type.create',
   'oauth.client.grant-type.delete',
   'oauth.client.grant-type.list',
   'oauth.client.grant-type.read',
   'oauth.client.grant-type.update',
   'oauth.client.list',
   'oauth.client.read',
   'oauth.client.scope.create',
   'oauth.client.scope.delete',
   'oauth.client.scope.list',
   'oauth.client.scope.read',
   'oauth.client.scope.update',
   'oauth.client.secret.list',
   'oauth.client.secret.read',
   'oauth.client.secret.rotate',
   'oauth.client.update',
   'oauth.post-logout-redirect-uri.create',
   'oauth.post-logout-redirect-uri.delete',
   'oauth.post-logout-redirect-uri.list',
   'oauth.post-logout-redirect-uri.read',
   'oauth.post-logout-redirect-uri.update',
   'oauth.redirect-uri.create',
   'oauth.redirect-uri.delete',
   'oauth.redirect-uri.list',
   'oauth.redirect-uri.read',
   'oauth.redirect-uri.update',
   'oauth.scope.create',
   'oauth.scope.delete',
   'oauth.scope.list',
   'oauth.scope.permission.create',
   'oauth.scope.permission.delete',
   'oauth.scope.permission.list',
   'oauth.scope.permission.read',
   'oauth.scope.permission.update',
   'oauth.scope.read',
   'oauth.scope.update',
];

export const GLOBAL_PERMISSIONS = [
   'auth.flow-stage.create',
   'auth.flow-stage.delete',
   'auth.flow-stage.list',
   'auth.flow-stage.read',
   'auth.flow-stage.update',
   'auth.flow.create',
   'auth.flow.delete',
   'auth.flow.list',
   'auth.flow.read',
   'auth.flow.update',
   'auth.session.revoke',
   'auth.session.revoke-user',
   'auth.stage.create',
   'auth.stage.delete',
   'auth.stage.list',
   'auth.stage.read',
   'auth.stage.update',
];

export const APP_READ_PERMISSIONS = [
   'workspace.list',
   'workspace.read',
   'workspace.user.list',
   'workspace.user.read',
   'workspace.invite.list',
   'workspace.invite.read',
   'user.address.list',
   'user.address.read',
   'user.document.list',
   'user.document.read',
   'user.email.list',
   'user.email.read',
   'user.list',
   'user.phone.list',
   'user.phone.read',
   'user.read',
   'application.list',
   'application.read',
   'application.role.list',
   'application.role.read',
   'application.permission.list',
   'application.permission.read',
   'application.role.permission.list',
   'application.role.permission.read',
];

export const APP_WRITE_PERMISSIONS = [
   'workspace.create',
   'workspace.update',
   'workspace.delete',
   'workspace.user.create',
   'workspace.user.update',
   'workspace.user.delete',
   'workspace.invite.create',
   'workspace.invite.update',
   'workspace.invite.delete',
   'workspace.invite.revoke',
   'user.address.create',
   'user.address.update',
   'user.address.delete',
   'user.create',
   'user.document.create',
   'user.document.update',
   'user.document.delete',
   'user.email.create',
   'user.email.update',
   'user.email.delete',
   'user.phone.create',
   'user.phone.update',
   'user.phone.delete',
   'user.update',
   'user.delete',
   'application.update',
   'application.role.create',
   'application.role.update',
   'application.role.delete',
   'application.permission.create',
   'application.permission.update',
   'application.permission.delete',
   'application.role.permission.create',
   'application.role.permission.update',
   'application.role.permission.delete',
];

export const APP_ADMIN_PERMISSIONS = [
   'oauth.client.list',
   'oauth.client.read',
   'oauth.client.create',
   'oauth.client.update',
   'oauth.client.delete',
   'oauth.client.secret.list',
   'oauth.client.secret.read',
   'oauth.client.secret.rotate',
   'oauth.redirect-uri.list',
   'oauth.redirect-uri.read',
   'oauth.redirect-uri.create',
   'oauth.redirect-uri.update',
   'oauth.redirect-uri.delete',
   'oauth.post-logout-redirect-uri.list',
   'oauth.post-logout-redirect-uri.read',
   'oauth.post-logout-redirect-uri.create',
   'oauth.post-logout-redirect-uri.update',
   'oauth.post-logout-redirect-uri.delete',
   'oauth.client.grant-type.list',
   'oauth.client.grant-type.read',
   'oauth.client.grant-type.create',
   'oauth.client.grant-type.update',
   'oauth.client.grant-type.delete',
   'oauth.scope.list',
   'oauth.scope.read',
   'oauth.scope.create',
   'oauth.scope.update',
   'oauth.scope.delete',
   'oauth.scope.permission.list',
   'oauth.scope.permission.read',
   'oauth.scope.permission.create',
   'oauth.scope.permission.update',
   'oauth.scope.permission.delete',
   'oauth.client.scope.list',
   'oauth.client.scope.read',
   'oauth.client.scope.create',
   'oauth.client.scope.update',
   'oauth.client.scope.delete',
   'workspace.permission.assign',
   'application.permission.assign',
];

const IAM_APPLICATION_PERMISSION_PREFIXES = [
   'application.',
   'application.role.',
   'application.permission.',
   'application.role.permission.',
];

export const IAM_APPLICATION_READ_PERMISSIONS = APP_READ_PERMISSIONS.filter(
   (name) =>
      IAM_APPLICATION_PERMISSION_PREFIXES.some((prefix) =>
         name.startsWith(prefix),
      ),
);

export const IAM_APPLICATION_WRITE_PERMISSIONS = Array.from(
   new Set([
      ...IAM_APPLICATION_READ_PERMISSIONS,
      ...APP_WRITE_PERMISSIONS.filter((name) =>
         IAM_APPLICATION_PERMISSION_PREFIXES.some((prefix) =>
            name.startsWith(prefix),
         ),
      ),
   ]),
);

export const DEFAULT_SCOPES = [
   {
      name: 'openid',
      description: 'OpenID Connect scope',
      isDefault: false,
      isActive: true,
   },
   {
      name: 'profile',
      description: 'Profile scope',
      isDefault: false,
      isActive: true,
   },
   {
      name: 'email',
      description: 'Email scope',
      isDefault: false,
      isActive: true,
   },
   {
      name: 'app:read',
      description: 'Leitura de dados da aplicação',
      isDefault: false,
      isActive: true,
   },
   {
      name: 'app:write',
      description: 'Escrita e gestão de dados da aplicação',
      isDefault: false,
      isActive: true,
   },
   {
      name: 'app:admin',
      description: 'Administração OAuth e configuração da aplicação',
      isDefault: false,
      isActive: true,
   },
   {
      name: 'iam:applications.read',
      description: 'Leitura global de aplicações no IAM',
      isDefault: false,
      isActive: true,
   },
   {
      name: 'iam:applications.write',
      description: 'Escrita global de aplicações no IAM',
      isDefault: false,
      isActive: true,
   },
];

export const CLIENT_ALLOWED_SCOPES = [
   'openid',
   'profile',
   'email',
   'app:read',
   'app:write',
   'app:admin',
   'iam:applications.read',
   'iam:applications.write',
];

export const ACL_PERMISSION_CODES = [
   'school.create',
   'school.update',
   'school.delete',
   'school.membership.manage',
   'course.create',
   'course.update',
   'course.delete',
   'course.membership.manage',
   'course.template.read',
   'course.template.manage',
   'klass.create',
   'klass.update',
   'klass.delete',
   'klass.membership.manage',
   'klass.exam.read',
   'klass.exam.manage',
   'klass.correction.read',
   'klass.correction.run',
   'klass.correction.review',
] as const;

type SeedAclRole = {
   code: string;
   scopeType: 'school' | 'course' | 'klass';
   rank: number;
   permissions: readonly string[];
};

export const ACL_ROLES: readonly SeedAclRole[] = [
   {
      code: 'school_owner',
      scopeType: 'school',
      rank: 400,
      permissions: ACL_PERMISSION_CODES,
   },
   {
      code: 'school_manager',
      scopeType: 'school',
      rank: 300,
      permissions: ACL_PERMISSION_CODES,
   },
   {
      code: 'school_editor',
      scopeType: 'school',
      rank: 200,
      permissions: [
         'school.update',
         'course.create',
         'course.update',
         'course.membership.manage',
         'course.template.read',
         'course.template.manage',
         'klass.create',
         'klass.update',
         'klass.exam.read',
         'klass.exam.manage',
         'klass.correction.read',
         'klass.correction.run',
         'klass.correction.review',
         'klass.membership.manage',
      ],
   },
   {
      code: 'school_viewer',
      scopeType: 'school',
      rank: 100,
      permissions: [],
   },
   {
      code: 'course_owner',
      scopeType: 'course',
      rank: 400,
      permissions: [
         'course.create',
         'course.update',
         'course.membership.manage',
         'course.template.read',
         'course.template.manage',
         'klass.create',
         'klass.update',
         'klass.delete',
         'klass.exam.read',
         'klass.exam.manage',
         'klass.correction.read',
         'klass.correction.run',
         'klass.correction.review',
         'klass.membership.manage',
      ],
   },
   {
      code: 'course_manager',
      scopeType: 'course',
      rank: 300,
      permissions: [
         'course.create',
         'course.update',
         'course.membership.manage',
         'course.template.read',
         'course.template.manage',
         'klass.create',
         'klass.update',
         'klass.delete',
         'klass.exam.read',
         'klass.exam.manage',
         'klass.correction.read',
         'klass.correction.run',
         'klass.correction.review',
         'klass.membership.manage',
      ],
   },
   {
      code: 'course_editor',
      scopeType: 'course',
      rank: 200,
      permissions: [
         'course.update',
         'course.template.read',
         'course.template.manage',
         'klass.create',
         'klass.update',
         'klass.exam.read',
         'klass.exam.manage',
         'klass.correction.read',
         'klass.correction.run',
      ],
   },
   {
      code: 'course_viewer',
      scopeType: 'course',
      rank: 100,
      permissions: [
         'course.template.read',
         'klass.exam.read',
         'klass.correction.read',
      ],
   },
   {
      code: 'klass_owner',
      scopeType: 'klass',
      rank: 400,
      permissions: [
         'klass.create',
         'klass.update',
         'klass.delete',
         'klass.exam.read',
         'klass.exam.manage',
         'klass.correction.read',
         'klass.correction.run',
         'klass.correction.review',
         'klass.membership.manage',
      ],
   },
   {
      code: 'klass_manager',
      scopeType: 'klass',
      rank: 300,
      permissions: [
         'klass.update',
         'klass.exam.read',
         'klass.exam.manage',
         'klass.correction.read',
         'klass.correction.run',
         'klass.correction.review',
         'klass.membership.manage',
      ],
   },
   {
      code: 'klass_editor',
      scopeType: 'klass',
      rank: 200,
      permissions: [
         'klass.update',
         'klass.exam.read',
         'klass.exam.manage',
         'klass.correction.read',
         'klass.correction.run',
      ],
   },
   {
      code: 'klass_viewer',
      scopeType: 'klass',
      rank: 100,
      permissions: ['klass.exam.read', 'klass.correction.read'],
   },
] as const;
